name: Deploy Lambda Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install Lambda Tools
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Build and Deploy
        working-directory: ./server
        run: |
          dotnet build
          dotnet lambda deploy-serverless \
            --stack-name charon-backend \
            --region $AWS_REGION \
            --s3-bucket $AWS_BUCKET \
            --s3-prefix charon-backend \
            --template serverless.template \
            --confirm-changeset \
            --capabilities CAPABILITY_IAM
